name: [Suggestion] 
description: Suggest a feature, plugin, or mechanic for the server.
body:
- type: textarea
  attributes:
    label: Is your suggestion related to a problem? Please describe below.
    description: "Please provide a clear and concise description of what the problem is. Put N/A if it is not related to a problem."
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: "Please provide a clear and concise description of what you want to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: "Please add any other context or screenshots about the suggestion here."
  validations:
    required: false